FROM node:10-alpine

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY tsconfig.json .
COPY ./packages/common /app/packages/common
COPY ./packages/web /app/packages/web

RUN yarn workspaces info
RUN yarn install 
RUN yarn web build 

ENV NODE_ENV production
RUN yarn web start 

CMD ["yarn", "start"]