version: "3"
services:
  ## PACKAGES

  gateway:
    #image: docker.pkg.github.com/olaven/paperpod/gateway:latest
    build:
      context: .
      dockerfile: ./Dockerfile.gateway
    ports:
      - 80:80
    environment:
      - PORT=80
      - API_PORT=8081
      - AUTHENTICATION_PORT=8082
      - WEB_PORT=3000
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    environment:
      - PORT=8081
      - JWT_SECRET="some super secret thing"
  authentication:
    build:
      context: .
      dockerfile: ./Dockerfile.authentication
    environment:
      - PORT=8082
      - JWT_SECRET="some super secret thing"
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web

  ## DATABASES

  # database_authentication:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  # database_api:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
