version: "3"
services:
  ## PACKAGES

  gateway:
    build: .
    env_file:
      - .env
    command: yarn gateway dev
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    volumes: # Sync everything but node modules
      - .:/instapod
      - /instapod/node_modules
      - /instapod/packages/gateway/node_modules
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
    working_dir: /instapod
  api:
    build: .
    env_file:
      - .env
    command: yarn api dev
    volumes: # Sync everything but node modules
      - /instapod/node_modules
      - /instapod/packages/api/node_modules
      - .:/instapod
    environment:
      - PORT=$API_PORT
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_api
      - MONGODB_PORT=$MONGODB_PORT #always true: https://hub.docker.com/_/mongo
    working_dir: /instapod
  converter:
    build: .
    env_file:
      - .env
    command: yarn converter dev
    volumes: # Sync everything but node modules
      - .:/instapod
      - /instapod/node_modules
      - /instapod/packages/converter/node_module
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
  authentication:
    build: .
    env_file:
      - .env # workaround to solve issues with node_modules being compiled on mac
    command: yarn authentication dev #bash -c "npm rebuild bcrypt --build-from-source && yarn authentication dev"
    volumes: # Sync everything but node modules
      - .:/instapod
      - /instapod/node_modules
      - /instapod/packages/authentication/node_modules
    environment:
      - PORT=$AUTHENTICATION_PORT
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_authentication
      - MONGODB_PORT=$MONGODB_PORT #always true: https://hub.docker.com/_/mongo
    working_dir: /instapod
  web:
    build: .
    env_file:
      - .env
    command: yarn web dev
    volumes: # Sync everything but node modules
      - .:/instapod
      - /instapod/node_modules
      - /instapod/packages/web/node_module
    working_dir: /instapod

  ## DATABASES

  database_authentication:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  database_api:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
