version: "3"
services:
  api:
    image: node:14
    env_file:
      - .env
    command: bash -c "yarn && yarn dev"
    ports:
      - 8080:8080
    volumes:
      - ./packages/api:/api
    working_dir: /api
    environment:
      - PORT=$API_PORT
  web:
    image: node:14
    env_file:
      - .env
    command: bash -c "yarn && yarn dev --port $WEB_PORT"
    ports:
      - 3000:3000
    volumes:
      - ./packages/web:/web
    working_dir: /web
