version: "3"
services:
  gateway:
    build: .
    env_file:
      - .env
    command: yarn gateway dev
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    volumes:
      - .:/paperpod
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - DOCS_PORT=$DOCS_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
      - NODE_ENV=dev
      - LOG_LEVEL=$LOG_LEVEL
    working_dir: /paperpod
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    env_file:
      - .env
    ports:
      - $API_PORT:$API_PORT
    command: yarn api dev
    volumes:
      - .:/paperpod
    environment:
      PORT: $API_PORT
      JWT_SECRET: $JWT_SECRET
      PGHOST: database
      PGDATABASE: $PGDATABASE
      PGUSER: $PGUSER

      PAPERPOD_SCHEMA: api
      PGPASSWORD: $PGPASSWORD
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      LOG_LEVEL: $LOG_LEVEL
    working_dir: /paperpod
  authentication:
    build: .
    env_file:
      - .env
    ports:
      - $AUTHENTICATION_PORT:$AUTHENTICATION_PORT
    command: yarn authentication dev
    volumes:
      - .:/paperpod
    environment:
      PORT: $AUTHENTICATION_PORT
      JWT_SECRET: $JWT_SECRET
      PGHOST: database
      PAPERPOD_SCHEMA: authentication
      PGDATABASE: $PGDATABASE
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      STRIPE_API_KEY: $STRIPE_API_KEY
      LOG_LEVEL: $LOG_LEVEL
    working_dir: /paperpod
  web:
    build: .
    env_file:
      - .env
    ports:
      - $WEB_PORT:$WEB_PORT
    command: yarn web dev
    volumes:
      - .:/paperpod
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
    working_dir: /paperpod

  docs:
    build: .
    env_file:
      - .env
    ports:
      - $DOCS_PORT:$DOCS_PORT
    command: yarn docs dev
    volumes:
      - .:/paperpod
    environment:
      - PORT=$DOCS_PORT
      - LOG_LEVEL=$LOG_LEVEL
    working_dir: /paperpod

  extension:
    build: .
    env_file:
      - .env
    command: yarn extension dev
    volumes:
      - ./packages/extension:/paperpod/packages/extension
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    working_dir: /paperpod

  # ultrahook.com receives webhook events from Stripe and
  # forwards them to my local dev server.
  # Stripe does not support localhost as an endpoint, so this is needed.
  ultrahook:
    build:
      dockerfile: ./Dockerfile.ultrahook
      context: .
    env_file:
      - .env
    command: ultrahook stripe http://gateway:${GATEWAY_PORT}/authentication/payment/webhook
    environment:
      - ULTRAHOOK_API_KEY=$ULTRAHOOK_API_KEY

  database:
    image: postgres:13
    command: postgres -N 500
    ports:
      - $PGPORT:$PGPORT
    environment:
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
