version: "3"
services:
  gateway:
    build: .
    env_file:
      - .env
    command: yarn gateway dev
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    volumes:
      - .:/paperpod
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - DOCS_PORT=$DOCS_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
      - NODE_ENV=dev
      - LOG_LEVEL=$LOG_LEVEL
    working_dir: /paperpod
  api:
    build: .
    env_file:
      - .env
    ports:
      - $API_PORT:$API_PORT
    command: yarn api dev
    volumes:
      - .:/paperpod
    environment:
      NODE_ENV: dev
      PORT: $API_PORT
      # IPC for user subscription check where JWT is not available
      AUTHENTICATION_INTERNAL_PORT: $AUTHENTICATION_INTERNAL_PORT
      ADMIN_USERNAME: $ADMIN_USERNAME
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      AUTHENTICATION_PORT: $AUTHENTICATION_PORT
      JWT_SECRET: $JWT_SECRET
      PGHOST: database
      PGDATABASE: $PGDATABASE
      PGUSER: $PGUSER
      PAPERPOD_SCHEMA: api
      PGPASSWORD: $PGPASSWORD
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      LOG_LEVEL: $LOG_LEVEL
    working_dir: /paperpod
  authentication:
    build: .
    env_file:
      - .env
    ports:
      - $AUTHENTICATION_PORT:$AUTHENTICATION_PORT
    command: yarn authentication dev
    volumes:
      - .:/paperpod
    environment:
      NODE_ENV: dev
      PORT: $AUTHENTICATION_PORT
      # IPC for user subscription check where JWT is not available
      INTERNAL_PORT: $AUTHENTICATION_INTERNAL_PORT
      ADMIN_USERNAME: $ADMIN_USERNAME
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      JWT_SECRET: $JWT_SECRET
      PGHOST: database
      PAPERPOD_SCHEMA: authentication
      PGDATABASE: $PGDATABASE
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      STRIPE_API_KEY: $STRIPE_API_KEY
      LOG_LEVEL: $LOG_LEVEL
    working_dir: /paperpod
  web:
    build: .
    env_file:
      - .env
    ports:
      - $WEB_PORT:$WEB_PORT
    command: yarn web dev --port $WEB_PORT
    volumes:
      - .:/paperpod
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
    working_dir: /paperpod

  docs:
    build: .
    env_file:
      - .env
    ports:
      - $DOCS_PORT:$DOCS_PORT
    command: yarn docs dev
    volumes:
      - .:/paperpod
    environment:
      - NODE_ENV=dev
      - PORT=$DOCS_PORT
      - LOG_LEVEL=$LOG_LEVEL
    working_dir: /paperpod

  extension:
    build: .
    env_file:
      - .env
    command: yarn extension dev
    volumes:
      - ./packages/extension:/paperpod/packages/extension
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    working_dir: /paperpod

  # ultrahook.com receives webhook events from Stripe and
  # forwards them to my local dev server.
  # Stripe does not support localhost as an endpoint, so this is needed.
  ultrahook:
    build:
      dockerfile: ./Dockerfile.ultrahook
      context: .
    env_file:
      - .env
    command: ultrahook stripe http://gateway:${GATEWAY_PORT}/authentication/payment/webhook
    environment:
      - ULTRAHOOK_API_KEY=$ULTRAHOOK_API_KEY

  database:
    image: postgres:13
    command: postgres -N 500
    ports:
      - $PGPORT:$PGPORT
    environment:
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD

  # This is here because some TF dependencies don't
  # support M1 macs. Use `de infrastructure /bin/sh`
  # to use Terraform through this container as a workaround :)
  infrastructure:
    build:
      context: .
      dockerfile: ./packages/infrastructure/Dockerfile
    env_file:
      - .env
    # keep it running to enable SSH-ing into it: https://stackoverflow.com/a/45450456/8543529
    command: tail -F anything
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      TF_VAR_stripe_api_token: $STRIPE_API_KEY
      TF_VAR_test_user_coupon_code: $STRIPE_COUPON_CODE

  metabase:
    image: metabase/metabase
    env_file:
      - .env
    ports:
      - $METABASE_PORT:3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=$PGDATABASE
      - MB_DB_PORT=$PGPORT
      - MB_DB_USER=$PGUSER
      - MB_DB_PASS=$PGPASSWORD
      - MB_DB_HOST=database
      - JAVA_TIMEZONE=Europe/Oslo
