version: "3"
services:
  ## PACKAGES

  gateway:
    build: .
    env_file:
      - .env
    command: yarn gateway dev
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    volumes:
      - .:/instapod
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
    working_dir: /instapod
  api:
    build: .
    env_file:
      - .env
    command: yarn api dev
    volumes:
      - .:/instapod
    environment:
      - PORT=$API_PORT
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_api
      - MONGODB_PORT=$MONGODB_PORT #always true: https://hub.docker.com/_/mongo
    working_dir: /instapod
  converter:
    build: .
    env_file:
      - .env
    command: yarn converter dev
    volumes:
      - .:/instapod
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
  authentication:
    build: .
    env_file:
      - .env
    command: yarn authentication dev
    volumes:
      - .:/instapod
    environment:
      - PORT=$AUTHENTICATION_PORT
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_authentication
      - MONGODB_PORT=$MONGODB_PORT #always true: https://hub.docker.com/_/mongo
    working_dir: /instapod
  web:
    build: .
    env_file:
      - .env
    command: yarn web dev
    volumes:
      - .:/instapod
    working_dir: /instapod

  ## DATABASES

  database_authentication:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  database_api:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
