version: "3"
services:
  gateway:
    build: .
    env_file:
      - .env
    command: yarn gateway dev
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    volumes:
      - .:/paperpod
    environment:
      - PORT=$GATEWAY_PORT
      - GATEWAY_HTTP_PORT=$GATEWAY_HTTP_PORT
      - WEB_PORT=$WEB_PORT
      - DOCS_PORT=$DOCS_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
    working_dir: /paperpod
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    env_file:
      - .env
    command: yarn api dev
    volumes:
      - .:/paperpod
    environment:
      - PORT=$API_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME_API
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_api
      - MONGODB_PORT=MONGODB_PORT_API
      - MONGODB_PROTOCOL=$MONGODB_PROTOCOL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    working_dir: /paperpod
  authentication:
    build: .
    env_file:
      - .env
    command: yarn authentication dev
    volumes:
      - .:/paperpod
    environment:
      - PORT=$AUTHENTICATION_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME_AUTHENTICATION
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_authentication
      - MONGODB_PORT=$MONGODB_PORT_AUTHENTICATION
      - MONGODB_PROTOCOL=$MONGODB_PROTOCOL
    working_dir: /paperpod
  web:
    build: .
    env_file:
      - .env
    command: yarn web dev
    volumes:
      - .:/paperpod
    working_dir: /paperpod

  docs: 
    build: . 
    env_file: 
      - .env 
    command: yarn docs dev 
    volumes:
      - .:/paperpod
    environment: 
      - PORT=$DOCS_PORT
    working_dir: /paperpod

  ## DATABASES

  database_authentication:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_NAME_AUTHENTICATION

  database_api:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_NAME_API
