version: "3"
services:
  ## PACKAGES

  gateway:
    build: .
    env_file:
      - .env
    command: bash -c "yarn && yarn gateway dev"
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    volumes:
      - .:/paperpod
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
    working_dir: /paperpod
  api:
    build: .
    env_file:
      - .env
    command: bash -c "yarn && yarn api dev"
    volumes:
      - .:/paperpod
    environment:
      - PORT=$API_PORT
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_api
      - MONGODB_PORT=$MONGODB_PORT #always true: https://hub.docker.com/_/mongo
    working_dir: /paperpod
  converter:
    build: .
    env_file:
      - .env
    command: bash -c "yarn && yarn converter dev"
    volumes:
      - .:/paperpod
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
  authentication:
    build: .
    env_file:
      - .env # workaround to solve issues with node_modules being compiled on mac
    command: bash -c "yarn && yarn authentication dev" #bash -c "npm rebuild bcrypt --build-from-source && yarn authentication dev""
    volumes:
      - .:/paperpod
    environment:
      - PORT=$AUTHENTICATION_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=database_authentication
      - MONGODB_PORT=$MONGODB_PORT #always true: https://hub.docker.com/_/mongo
    working_dir: /paperpod
  web:
    build: .
    env_file:
      - .env
    command: bash -c "yarn && yarn web dev"
    volumes:
      - .:/paperpod
    working_dir: /paperpod

  ## DATABASES

  database_authentication:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

  database_api:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
