# run with: env GATEWAY_PORT=8080 WEB_PORT=3000 API_PORT=8081 AUTHENTICATION_PORT=8082 JWT_SECRET="jwt-token-secret-stack" MONGODB_NAME="SOMEMONONAME"MONGODB_USERNAME="SOMEMONGOUSERNAME" MONGODB_PASSWORD="SOMEMONGOPASSWORD" MONGODB_HOST="SOMEMOGNOHST" MONGODB_PORT=27017 AWS_ACCESS_KEY_ID="SOME ACCESS KEY" AWS_SECRET_ACCESS_KEY="SOME SECRET KEY" docker stack deploy -c stack.yml paperpod
version: "3"
services:
  gateway:
    command: yarn gateway start
    image: olaven/paperpod-gateway
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
  api:
    image: olaven/paperpod-api
    environment:
      - PORT=$API_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT # 27017
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  authentication:
    image: olaven/paperpod-authentication
    environment:
      - PORT=$AUTHENTICATION_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT # 27017
  web:
    image: olaven/paperpod-web
