version: "3"
services:
  gateway:
    image: docker.pkg.github.com/olaven/paperpod/gateway:fix-automatic-tagging-of-docker-images
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
  api:
    image: docker.pkg.github.com/olaven/paperpod/api:fix-automatic-tagging-of-docker-images
    environment:
      - PORT=$API_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT # 27017
      - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
  authentication:
    image: docker.pkg.github.com/olaven/paperpod/authentication:fix-automatic-tagging-of-docker-images
    environment:
      - PORT=$AUTHENTICATION_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT # 27017
  web:
    image: docker.pkg.github.com/olaven/paperpod/web:fix-automatic-tagging-of-docker-images
