version: "3"
services:
  nginx:
      image: nginx:latest
      ports: 
       - 80:80
  gateway: 
    image: docker.pkg.github.com/olaven/paperpod/gateway:latest
    ports: 
      - 8080:8080
  authentication:
    image: docker.pkg.github.com/olaven/paperpod/authentication:latest
  api:
    image: docker.pkg.github.com/olaven/paperpod/api:latest
  web:
    image: docker.pkg.github.com/olaven/paperpod/web:latest
