openapi: 3.0.0
info:
  title: Paperpod API
  description: API for interacting with Paperpod 
  version: 0.0.1
servers:
  - url: https://application.paperpod.fm
    description: Production server for Paperpod
paths:
  /api: 
    $ref: "./api/api.yml"
  /authentication: 
    $ref: "./authentication/authentication.yml"

    
