FROM node:10-alpine

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./packages/common /app/packages/common
COPY ./packages/web /app/packages/web

RUN yarn install  

ENV NODE_ENV production
CMD ["yarn", "web", "start"]