FROM node:12-alpine

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./packages/common /app/packages/common
COPY ./packages/server /app/packages/server
COPY ./packages/authentication /app/packages/authentication

RUN yarn install 

ENV NODE_ENV production
CMD ["yarn", "authentication", "start"]