FROM node:10-alpine

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./packages/ui ./packages/ui
COPY ./packages/frontend ./packages/frontend
COPY ./packages/common ./packages/common
COPY ./packages/web ./packages/web

RUN yarn install  
RUN yarn web build 
ENV NODE_ENV production
CMD ["yarn", "web", "start"]