FROM node:10-alpine

WORKDIR /app

COPY ../package.json .
COPY ../yarn.lock .
COPY ../tsconfig.json .
COPY ../packages/common /app/packages/common
COPY ../packages/converter /app/packages/converter
COPY ../packages/api /app/packages/api

RUN yarn install
RUN yarn api build 

ENV NODE_ENV production
RUN yarn api start 

CMD ["yarn", "start"]