version: "3"
services:
  gateway:
    image: docker.pkg.github.com/olaven/paperpod/gateway:latest
  authentication:
    image: docker.pkg.github.com/olaven/paperpod/authentication:latest
  api:
    image: docker.pkg.github.com/olaven/paperpod/api:latest
  web:
    image: docker.pkg.github.com/olaven/paperpod/web:latest
