version: "3"
services:
  gateway:
    image: docker.pkg.github.com/olaven/paperpod/gateway:latest
    ports:
      - 8080:8080
      # - target: 8080
      #   published: 8080
      #   mode: host
  networks:
    - paperpod_network
  authentication:
    image: docker.pkg.github.com/olaven/paperpod/authentication:latest
  api:
    image: docker.pkg.github.com/olaven/paperpod/api:latest
  web:
    image: docker.pkg.github.com/olaven/paperpod/web:latest

networks: paperpod_network
