FROM node:10-alpine

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./packages/common /app/packages/common
COPY ./packages/authentication /app/packages/authentication

RUN yarn install --production

ENV NODE_ENV production
CMD ["yarn", "authentication", "start"]