FROM node:19-alpine

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./packages/common /app/packages/common
COPY ./packages/server /app/packages/server
COPY ./packages/gateway /app/packages/gateway

RUN yarn install

ENV NODE_ENV production
CMD ["yarn", "gateway", "start"]