FROM node:10-alpine

WORKDIR /app

COPY ../package.json .
COPY ../yarn.lock .
COPY ../tsconfig.json .
COPY ../packages/common /app/packages/common
COPY ../packages/gateway /app/packages/gateway

RUN yarn install
RUN yarn workspaces run build

ENV NODE_ENV production
RUN yarn gateway start 

CMD ["yarn", "start"]