FROM buildkite/puppeteer:8.0.0

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./packages/common /app/packages/common
COPY ./packages/server /app/packages/server
COPY ./packages/converter /app/packages/converter
COPY ./packages/api /app/packages/api

RUN yarn install 

ENV NODE_ENV production

CMD ["yarn", "api", "start"]