version: "3"
services:
  gateway:
    image: olaven/paperpod-gateway@$GATEWAY_DIGEST
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
      - $GATEWAY_HTTP_PORT:$GATEWAY_HTTP_PORT
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
    #volumes: # FIXME: add once certbot has run
    #  - /etc/letsencrypt/live/application.paperpod.fm/privkey.pem:/etc/letsencrypt/live/application.paperpod.fm/privkey.pem
    #  - /etc/letsencrypt/live/application.paperpod.fm/cert.pem:/etc/letsencrypt/live/application.paperpod.fm/cert.pem
    #  - /etc/letsencrypt/live/application.paperpod.fm/chain.pem:/etc/letsencrypt/live/application.paperpod.fm/chain.pem
  api:
    image: olaven/paperpod-api@$API_DIGEST
    environment:
      - PORT=$API_PORT
      - JWT_SECRET=$JWT_SECRET
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - PGSSLMODE=require
      - PGOPTIONS="-c search_path='api'"
      - DATABASE_CA=$DATABASE_CA
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  authentication:
    image: olaven/paperpod-authentication@$AUTHENTICATION_DIGEST
    environment:
      - PORT=$AUTHENTICATION_PORT
      - JWT_SECRET=$JWT_SECRET
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - PGSSLMODE=require
      - PGOPTIONS="-c search_path='authentication'"
      DATABASE_CA: $DATABASE_CA
  web:
    image: olaven/paperpod-web@$WEB_DIGEST
