version: "3"
services:
  gateway:
    image: olaven/paperpod-gateway@$GATEWAY_DIGEST
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
  api:
    image: olaven/paperpod-api@$API_DIGEST
    environment:
      - PORT=$API_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME_API
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT_API # 27017
      - MONGODB_PROTOCOL=$MONGODB_PROTOCOL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  authentication:
    image: olaven/paperpod-authentication@$AUTHENTICATION_DIGEST
    environment:
      - PORT=$AUTHENTICATION_PORT
      - JWT_SECRET=$JWT_SECRET
      - MONGODB_NAME=$MONGODB_NAME_AUTHENTICATION
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT_AUTHENTICATION # 27017
      - MONGODB_PROTOCOL=$MONGODB_PROTOCOL
  web:
    image: olaven/paperpod-web@$WEB_DIGEST
