version: "3"
services:
  gateway:
    image: olaven/paperpod-gateway@$GATEWAY_DIGEST
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    environment:
      - PORT=$GATEWAY_PORT
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
      - AUTHENTICATION_PORT=$AUTHENTICATION_PORT
      - DOCS_PORT=$DOCS_PORT
  api:
    image: olaven/paperpod-api@$API_DIGEST
    environment:
      - PORT=$API_PORT
      - NODE_ENV=production
      - JWT_SECRET=$JWT_SECRET
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - PGSSLMODE=require
      - PAPERPOD_SCHEMA=api
      - DATABASE_CA=$DATABASE_CA
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  authentication:
    image: olaven/paperpod-authentication@$AUTHENTICATION_DIGEST
    environment:
      - PORT=$AUTHENTICATION_PORT
      - NODE_ENV=production
      - JWT_SECRET=$JWT_SECRET
      - STRIPE_API_KEY=$STRIPE_API_KEY
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - PGSSLMODE=require
      - PAPERPOD_SCHEMA=authentication
      - DATABASE_CA=$DATABASE_CA
  web:
    image: olaven/paperpod-web@$WEB_DIGEST
    environment:
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
  docs:
    image: olaven/paperpod-docs@$DOCS_DIGEST
    environment:
      - PORT=$DOCS_PORT
