on:
  push:
    branches:
      - main
      - setup/terraform #TODO: Remove after tesing

jobs:
  apply-infrastructure:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_SECRET_ACCESS_KEY }}
      TF_VAR_stripe_api_token: ${{ secrets.TF_VAR_stripe_api_token }}
      TF_VAR_test_user_coupon_code: ${{ secrets.TF_VAR_test_user_coupon_code }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: initializing Terraform
        run: terraform init -no-color
        working-directory: ./infrastructure
      - name: Applying infrastructure
        run: terraform apply -no-color
        working-directory: ./infrastructure
