name: Deploy

on:
  push:
    branches:
      - main
      - feature/ci-for-deployment

jobs:
  deploy-with-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            git clone https://github.com/olaven/paperpod
            cd paperpod
            chmod +x ./scripts/setup-firewall-manager.sh
            ./scripts/setup-firewall-manager.sh
            chmod +x ./scripts/stack.sh
            ./scripts/stack.sh
        env:
          FOO: "BAR"
          BAR: "FOO"
          SHA: ${{ github.sha }}
