name: Deploy

on:
  push:
    branches:
      - main
      - feature/ci-for-deployment

jobs:
  deploy-with-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true # git clone https://github.com/olaven/paperpod # alread run. Figure out how to be state-agnostic?
          script: |
            cd paperpod 
            git pull 
            env \
              GATEWAY_PORT=80 \
              WEB_PORT=3000 \
              API_PORT=8081 \
              AUTHENTICATION_PORT=8082 \
              JWT_SECRET="jwt-token-secret-stack" \
              MONGODB_NAME_API="api" \
              MONGODB_NAME_AUTHENTICATION="authentication" \
              MONGODB_USERNAME="SOMEMONGOUSERNAME" \
              MONGODB_PASSWORD="SOMEMONGOPASSWORD" \
              MONGODB_HOST="some mongo host" \
              MONGODB_PORT=27017 \
              AWS_ACCESS_KEY_ID="SOME ACCESS KEY" \
              AWS_SECRET_ACCESS_KEY="SOME SECRET KEY" \
              docker stack deploy -c $HOME/paperpod/scripts/stack.yml paperpod;
        env:
          FOO: "BAR"
          BAR: "FOO"
          SHA: ${{ github.sha }}
