name: Docker

on:
  push:
    branches:
      - main
      - research/deployment #temporary

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build-and-push-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./dockerfiles/Dockerfile.web
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/web
          tag_with_sha: true
          tag_with_ref: true
