on:
  push:
    branches:
      - feature/move_to_postgres

jobs:
  apply-infrastructure:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_SECRET_ACCESS_KEY }}
      TF_VAR_stripe_api_token: ${{ secrets.TF_VAR_stripe_api_token }}
      TF_VAR_github_api_token: ${{ secrets.TF_VAR_github_api_token }}
      TF_VAR_test_user_coupon_code: ${{ secrets.TF_VAR_test_user_coupon_code }}
      TF_VAR_do_token: ${{ secrets.TF_VAR_do_token }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_wrapper: false
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: initializing Terraform
        run: yarn infrastructure terraform:assumeenv init -no-color
      - name: Applying infrastructure
        run: yarn infrastructure terraform:assumeenv apply -auto-approve -no-color
      - name: Call terraform output
        id: infrastructure-output
        run: |
          output_from_terraform=$(yarn infrastructure terraform:assumeenv output database_uri)
          some_hardcoded_output="this is some hardcoded output created for test"
          echo $output_from_terraform
          echo $some_hardcoded_output
          echo "::set-output name=first_output::$output_from_terraform"
          echo "::set-output name=second_output::$some_hardcoded_output"
    outputs:
      first_output: ${{ steps.infrastructure-output.outputs.first_output }}
      second_output: ${{ steps.infrastructure-output.outputs.second_output }}
  nextjob: 
    runs-on: ubuntu-latest
    needs: [apply-infrastructure]
    steps: 
      - run: | 
          echo "Got output from previous step, again gotten from terraform"
          echo ${{ needs.apply-infrastructure.outputs.first_output}}
          echo "Got output from previous step, hardcoded"
          echo ${{ needs.apply-infrastructure.outputs.second_output}}