name: Tests

on: [push]

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: node:14
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13
        # Provide the password for postgres
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:14
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn api test:ci
        env:
          JWT_SECRET: The JWT secret in CI test environment for api tests
          PGHOST: postgres
          PGUSER: ci_user
          PGPASSWORD: ci_password
          PAPERPOD_SCHEMA: api

  test-authentication:
    runs-on: ubuntu-latest
    container: node:14
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
          TEST_STRIPE_API_KEY: ${{ secrets.TEST_STRIPE_API_KEY }}
          ADMIN_USERNAME: test_admin_username
          ADMIN_PASSWORD: test_admin_password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:14
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn authentication test
        env:
          JWT_SECRET: The JWT secret in CI test environment for authentication tests
          PGHOST: postgres
          PGUSER: ci_user
          PGPASSWORD: ci_password
          PAPERPOD_SCHEMA: authentication
  test-converter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn converter test
        env:
          JWT_SECRET: The JWT secret in CI test environment for converter tests
  test-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn common test
        env:
          JWT_SECRET: The JWT secret in CI test environment for common tests
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn server test
        env:
          JWT_SECRET: The JWT secret in CI test environment for server tests
  test-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn web test
  test-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:14
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        # FIXME: figure out why the
        # main-import does not work in CI.
        # Can reproduce with `act -j test-extension`
        run: echo "Not running extension tests."
        #run: yarn extension test
