on:
  push:
    branches:
      - feature/ci_deployment_to_digitalocean

jobs:
  update-infrastructure-and-deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_SECRET_ACCESS_KEY }}
      TF_VAR_stripe_api_token: ${{ secrets.TF_VAR_stripe_api_token }}
      TF_VAR_github_api_token: ${{ secrets.TF_VAR_github_api_token }}
      TF_VAR_test_user_coupon_code: ${{ secrets.TF_VAR_test_user_coupon_code }}
      TF_VAR_do_token: ${{ secrets.TF_VAR_do_token }}
      TF_VAR_droplet_username: ${{ secrets.TF_VAR_droplet_username }}
      TF_VAR_droplet_password: ${{ secrets.TF_VAR_droplet_password }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_wrapper: false
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: initializing Terraform
        run: yarn infrastructure terraform:assumeenv init -no-color
      - name: Applying infrastructure
        run: yarn infrastructure terraform:assumeenv apply -auto-approve -no-color
      - name: Call terraform output
        id: infrastructure-output
        # the below 1. gets output 2. takes the like with output value 3. removes the "yarn done"-ending
        # echo $(yarn infrastructure terraform output database_uri --raw  | tail -2 | sed "s/Done.*//g")
        run: |
          database_uri_from_terraform=$(yarn infrastructure terraform:assumeenv output database_uri | tail -2 | sed "s/Done.*//g")
          droplet_id_from_terraform=$(yarn infrastructure terraform:assumeenv output droplet_id | tail -2 | sed "s/Done.*//g")
          echo "::set-output name=database_uri::$database_uri_from_terraform"
          echo "::set-output name=droplet_id::$droplet_id_from_terraform"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.TF_VAR_droplet_username }}
          password: ${{ secrets.TF_VAR_droplet_password }}
          port: 22
          script: whoami

      # NOTE: TESTING WIHT DOCTL
      # - name: Install doctl
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.TF_VAR_do_token }}
      # - run: |  
      #     echo "Got database_uri / droplet_id"
      #     echo ${{ steps.infrastructure-output.outputs.database_uri }}
      #     echo ${{ steps.infrastructure-output.outputs.droplet_id }}
      #     doctl compute ssh ${{ steps.infrastructure-output.outputs.droplet_id }} --ssh-command ls
