name: Validate Infrastructure

on: [push]

jobs:
  plan-infrastructure:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_SECRET_ACCESS_KEY }}
      TF_VAR_stripe_api_token: ${{ secrets.TF_VAR_stripe_api_token }}
      TF_VAR_test_user_coupon_code: ${{ secrets.TF_VAR_test_user_coupon_code }}
      TF_VAR_do_token: ${{ secrets.TF_VAR_do_token }}
      TF_VAR_stripe_api_key: ${{ secrets.STRIPE_API_KEY }}
      TF_VAR_stripe_publishable_key: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      TF_VAR_gateway_port: ${{ secrets.GATEWAY_PORT }}
      TF_VAR_web_port: ${{ secrets.WEB_PORT }}
      TF_VAR_docs_port: ${{ secrets.DOCS_PORT }}
      TF_VAR_api_port: ${{ secrets.API_PORT }}
      TF_VAR_authentication_port: ${{ secrets.AUTHENTICATION_PORT }}
      TF_VAR_log_level: ${{ secrets.LOG_LEVEL }}
      TF_VAR_authentication_internal_port: ${{ secrets.AUTHENTICATION_INTERNAL_PORT }}
      TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}
      TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        - node-version: [19.x]
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: initializing Terraform
        run: yarn infrastructure terraform:assumeenv init -no-color
      - name: validating syntax
        run: yarn infrastructure terraform:assumeenv validate -no-color
      - name: plan infrastructure changes
        run: yarn infrastructure terraform:assumeenv plan -no-color
