name: Validate Infrastructure

on: [push]

jobs:
  plan-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: initializing Terraform
        run: terraform init -no-color
        working-directory: ./infrastructure
      - name: validating syntax
        run: terraform validate -no-color
        working-directory: ./infrastructure
      - name: plan infrastructure changes
        run: terraform plan -no-color
        working-directory: ./infrastructure
